### ISSUE TITLE
Doesn't support (test) overseas territories

### ISSUE THREAD

**Issue by petevb** [NewOrbit/NewOrbit.PostcodeParser.UK#1]
@flytzen : Just to check:

1. We're not testing UK's overseas territories, e.g. Falklands ("FIQQ 1ZZ") nor British Forces Post Offices (BFPO nn).  Is that by design?
1. Also Santander/Girobank's a weird one, "GIR 0AA".  Presumably you're okay not to accept that?

Ta, Pete

**Comment by DarranShepherd** [comment]
Looks like there are a few "vanity" postcodes. https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Special_cases

**Comment by petevb** [comment]
Thanks - good list!  Looks like they *mostly* conform to the "standard" variations of AA99 9AA, especially within the British Isles, but it's the overseas ones that could cause problems.  I think we need to understand the requirements.

**Comment by flytzen** [comment]
Man I love working with smart people :)
I had no idea about those. They *do* make a case for having this as a proper package. Overseas Territories are not technically UK, I think, but let's see what we can do...
